# .github/workflows/publish-to-pypi.yml

name: Publish Python Package to PyPI

on:
  # Activa el workflow cada vez que se crea un nuevo release en GitHub
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Puedes ajustar la versión de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Usaremos un token de API de PyPI
          password: ${{ secrets.PYPI_API_TOKEN }}